config/routes.rb
Rails.application.routes.draw do
  resources :our_services
  resources :abouts
  resources :homes
  resources :carts
  resources :cart_items, only: [:create, :destroy]
  resources :reviews
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  def add_product(product_params)
    current_item = cart_items.find_by(product_id: product_params[:cart_items][:product_id])
    if current_item
      # current_item.quantity += product_params[:cart_items][:quantity].to_i
      current_item.save
    else
      new_item = cart_items.create(product_id: product_params[:cart_items][:product_id],
                                  cart_id: self.id)
                                  # quantity: product_params[:cart_items][:quantity],
    end
    new_item
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/our_service.rb
class OurService < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true, greater_than: 0}
  has_many :reviews, dependent: :destroy

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    # @cart =  current_user.cart
    # user has_one cart
    @cart = Cart.first
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/our_services_helper.rb
module OurServicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
  </style>
         <div class="nav-bar">        
           <div id="search">
            <div class="container">
  <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <div id="imaginary_container"> 
                <div class="input-group stylish-input-group">
                    <input type="text" class="form-control"  placeholder="Search" >
                    <span class="input-group-addon">
                        <button type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>  
                    </span>
                </div>
            </div>
        </div>
  </div>
</div>
           <span id="leaf"><i class="fas fa-leaf" fa-lg></i><em>Rainforest</em></span>
           </div>
           <div>
             <p class="active">
               <span class="left">
                 <span><%=link_to "HOME", products_path %> </span>
                 <span><%=link_to "ABOUT", abouts_path %></span>
                 <span><%=link_to "OUR SERVICES", our_services_path %></span>
               </span>
               <span class="right">
                 <span><%=link_to"MENS" %></span>
                 <span><%=link_to"WOMENS" %></span>
                 <span><%=link_to"GEAR" %></span>
               </span>
               <span class="cart">
                 <span><%=link_to carts_path do %>
                    <i class="fas fa-shopping-cart"></i>
                  <% end %>
                </span>
                 <span><a href="#">CONTACT</a></span>
               </span>
             </p>

            </div>
         </div>
    <%= yield %>  
    <footer class="footer">
      <div class="container">
        <div class="row">
               <div class="col">
                <ul>
                 <u><b><%=link_to "GET TO KNOW US", our_services_path %></b></u>
                 <li stile="color:white"><%=link_to "Careers", our_services_path %></li>
                 <li><%=link_to "Investor Relations", our_services_path %></li>
                 <li><%=link_to "Rainforest Devices", our_services_path %></li>
                 <li><%=link_to "About Rainforest", our_services_path %></li>
               </ul>
               </div>
               <div class="col">
                <ul>
                 <u><b><%=link_to"MAKE MONEY WITH US" %></b></u>
                 <li><%=link_to"Sell on Rainforest" %></li>
                 <li><%=link_to"Become an Affiliate" %></li>
                 <li><%=link_to"Sell your Services on Rainforest" %></li>
                 <li><%=link_to"Advertise Your Products" %></li>
               </ul>
               </div>
               <div class="col">
                <ul>
                 <u><b><%=link_to"PAYMENT PRODUCTS" %></b></u>
                 <li><%=link_to"Rainforest Rewards" %></li>
                 <li><%=link_to"Rainforest Corporate Credit Line" %></li>
                 <li><%=link_to"Shop with Points" %></li>
                 <li><%=link_to"Reload Your Balance" %></li>
               </ul>
               </div>
               <div class="col">
                <ul>
                 <u><b><%=link_to"LET US HELP YOU" %></b></u>
                 <li><%=link_to"Your Account" %></li>
                 <li><%=link_to"Your Orders" %></li>
                 <li><%=link_to"Shipping Rates and Policies" %></li>
                 <li><%=link_to"Help" %></li>
               </ul>
             </div>
           </div>
           </div>
    </footer>
  </body>
</html>